// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: grpcstruct/grpcstruct.proto

package grpcstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateGroup string   `protobuf:"bytes,1,opt,name=template_group,json=templateGroup,proto3" json:"template_group,omitempty"`
	TemplateName  string   `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	To            []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	DataJson      []byte   `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
}

func (x *MailTemplateRequest) Reset() {
	*x = MailTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcstruct_grpcstruct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailTemplateRequest) ProtoMessage() {}

func (x *MailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcstruct_grpcstruct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailTemplateRequest.ProtoReflect.Descriptor instead.
func (*MailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_grpcstruct_grpcstruct_proto_rawDescGZIP(), []int{0}
}

func (x *MailTemplateRequest) GetTemplateGroup() string {
	if x != nil {
		return x.TemplateGroup
	}
	return ""
}

func (x *MailTemplateRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MailTemplateRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MailTemplateRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type MailTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *MailTemplateResponse) Reset() {
	*x = MailTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcstruct_grpcstruct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailTemplateResponse) ProtoMessage() {}

func (x *MailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcstruct_grpcstruct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailTemplateResponse.ProtoReflect.Descriptor instead.
func (*MailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_grpcstruct_grpcstruct_proto_rawDescGZIP(), []int{1}
}

func (x *MailTemplateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_grpcstruct_grpcstruct_proto protoreflect.FileDescriptor

var file_grpcstruct_grpcstruct_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67,
	0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x4d, 0x61,
	0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x14, 0x4d, 0x61,
	0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x32, 0x59, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a,
	0x0d, 0x2e, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcstruct_grpcstruct_proto_rawDescOnce sync.Once
	file_grpcstruct_grpcstruct_proto_rawDescData = file_grpcstruct_grpcstruct_proto_rawDesc
)

func file_grpcstruct_grpcstruct_proto_rawDescGZIP() []byte {
	file_grpcstruct_grpcstruct_proto_rawDescOnce.Do(func() {
		file_grpcstruct_grpcstruct_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcstruct_grpcstruct_proto_rawDescData)
	})
	return file_grpcstruct_grpcstruct_proto_rawDescData
}

var file_grpcstruct_grpcstruct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcstruct_grpcstruct_proto_goTypes = []any{
	(*MailTemplateRequest)(nil),  // 0: grpcstruct.MailTemplateRequest
	(*MailTemplateResponse)(nil), // 1: grpcstruct.MailTemplateResponse
}
var file_grpcstruct_grpcstruct_proto_depIdxs = []int32{
	0, // 0: grpcstruct.MailTemplate.Send:input_type -> grpcstruct.MailTemplateRequest
	1, // 1: grpcstruct.MailTemplate.Send:output_type -> grpcstruct.MailTemplateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcstruct_grpcstruct_proto_init() }
func file_grpcstruct_grpcstruct_proto_init() {
	if File_grpcstruct_grpcstruct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcstruct_grpcstruct_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MailTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcstruct_grpcstruct_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MailTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcstruct_grpcstruct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcstruct_grpcstruct_proto_goTypes,
		DependencyIndexes: file_grpcstruct_grpcstruct_proto_depIdxs,
		MessageInfos:      file_grpcstruct_grpcstruct_proto_msgTypes,
	}.Build()
	File_grpcstruct_grpcstruct_proto = out.File
	file_grpcstruct_grpcstruct_proto_rawDesc = nil
	file_grpcstruct_grpcstruct_proto_goTypes = nil
	file_grpcstruct_grpcstruct_proto_depIdxs = nil
}
