// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: grpcstruct/grpcstruct.proto

package grpcstruct

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailTemplate_Send_FullMethodName = "/grpcstruct.MailTemplate/Send"
)

// MailTemplateClient is the client API for MailTemplate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailTemplateClient interface {
	Send(ctx context.Context, in *MailTemplateRequest, opts ...grpc.CallOption) (*MailTemplateResponse, error)
}

type mailTemplateClient struct {
	cc grpc.ClientConnInterface
}

func NewMailTemplateClient(cc grpc.ClientConnInterface) MailTemplateClient {
	return &mailTemplateClient{cc}
}

func (c *mailTemplateClient) Send(ctx context.Context, in *MailTemplateRequest, opts ...grpc.CallOption) (*MailTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailTemplateResponse)
	err := c.cc.Invoke(ctx, MailTemplate_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailTemplateServer is the server API for MailTemplate service.
// All implementations must embed UnimplementedMailTemplateServer
// for forward compatibility.
type MailTemplateServer interface {
	Send(context.Context, *MailTemplateRequest) (*MailTemplateResponse, error)
	mustEmbedUnimplementedMailTemplateServer()
}

// UnimplementedMailTemplateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailTemplateServer struct{}

func (UnimplementedMailTemplateServer) Send(context.Context, *MailTemplateRequest) (*MailTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMailTemplateServer) mustEmbedUnimplementedMailTemplateServer() {}
func (UnimplementedMailTemplateServer) testEmbeddedByValue()                      {}

// UnsafeMailTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailTemplateServer will
// result in compilation errors.
type UnsafeMailTemplateServer interface {
	mustEmbedUnimplementedMailTemplateServer()
}

func RegisterMailTemplateServer(s grpc.ServiceRegistrar, srv MailTemplateServer) {
	// If the following call pancis, it indicates UnimplementedMailTemplateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailTemplate_ServiceDesc, srv)
}

func _MailTemplate_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailTemplateServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailTemplate_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailTemplateServer).Send(ctx, req.(*MailTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailTemplate_ServiceDesc is the grpc.ServiceDesc for MailTemplate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailTemplate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcstruct.MailTemplate",
	HandlerType: (*MailTemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MailTemplate_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcstruct/grpcstruct.proto",
}
